Allow passing a directory

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -1,5 +1,4 @@
 #!/bin/sh
-
 tests_root="$(dirname "$0")"
 program="$tests_root/../index.js"
 pass_symbol="😊 [32mPASS"
@@ -24,10 +23,10 @@ for baddy in "$tests_root"/bad/*; do
 	# redirect errors to the fourth file descriptor so users can turn it on with
 	# ./test 4>&2
 	if { "$program" "$baddy"; } 1>/dev/null 2>&4; then
-		>&2 echo "$fail_symbol bad schema '$name' seemed good"
+		>&2 echo "$fail_symbol bad origami.json '$name' seemed good"
 		exit_code=1
 	else
-		>&2 echo "$pass_symbol bad schema '$name' seemed bad"
+		>&2 echo "$pass_symbol bad origami.json '$name' seemed bad"
 	fi
 done
 
@@ -36,9 +35,9 @@ for goody in "$tests_root"/good/*; do
 	# redirect errors to the third file descriptor so users can turn it on
 	# with ./test 3>&2
 	if { "$program" "$goody"; } 1>/dev/null 2>&3; then
-		>&2 echo "$pass_symbol good schema '$name' seemed good"
+		>&2 echo "$pass_symbol good origami.json '$name' seemed good"
 	else
-		>&2 echo "$fail_symbol good schema '$name' seemed bad"
+		>&2 echo "$fail_symbol good origami.json '$name' seemed bad"
 		exit_code=1
 	fi
 done
